# Generated by Django 3.2.4 on 2021-10-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0004_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
