# Generated by Django 3.2.4 on 2021-10-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0006_alter_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flag',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
