# Generated by Django 3.2.4 on 2021-10-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0007_order_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentt',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='flag',
            field=models.CharField(choices=[('CM', 'Completed'), ('P', 'Pending'), ('C', 'Canceled')], max_length=2),
        ),
    ]
