# Generated by Django 3.2.4 on 2021-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0010_alter_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
