# Generated by Django 3.2.4 on 2021-10-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0038_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profilepic/default.jpg', null=True, upload_to='pic'),
        ),
    ]
