# Generated by Django 3.2.4 on 2022-01-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0052_auto_20220124_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification',
            field=models.CharField(choices=[('V', 'Verified'), ('NV', 'Not Verified')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no_verification',
            field=models.CharField(choices=[('V', 'Verified'), ('NV', 'Not Verified')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
