# Generated by Django 3.2.4 on 2022-01-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0053_auto_20220124_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verification',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_no_verification',
        ),
    ]
