# Generated by Django 3.2.4 on 2022-01-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0060_auto_20220124_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email_verification',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='phone_no_verification',
        ),
    ]
