# Generated by Django 3.2.4 on 2022-01-24 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WeDeliver', '0066_auto_20220124_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verification',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_no_verification',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
