# Generated by Django 3.2.4 on 2022-01-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0071_rename_email_no_otp_profile_email_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
