# Generated by Django 3.2.4 on 2022-02-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0077_auto_20220216_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_point_phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
