# Generated by Django 3.2.4 on 2022-02-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0078_alter_order_pickup_point_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_point_phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
