# Generated by Django 3.2.4 on 2022-02-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0080_auto_20220218_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_price', models.FloatField()),
                ('food_price', models.FloatField()),
                ('package_price', models.FloatField()),
            ],
        ),
    ]
