# Generated by Django 3.2.4 on 2021-09-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0002_rename_login_form_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_up',
        ),
    ]
