# Generated by Django 3.2.4 on 2021-10-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0008_auto_20211011_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentt',
            new_name='payment',
        ),
    ]
