# Generated by Django 3.2.4 on 2021-10-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0013_contactus_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
