# Generated by Django 3.2.4 on 2021-10-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0014_auto_20211016_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
