# Generated by Django 3.2.4 on 2021-10-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0017_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
