# Generated by Django 3.2.4 on 2021-10-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0021_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
