# Generated by Django 3.2.4 on 2021-10-27 15:51

import WeDeliver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0047_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=WeDeliver.models.pic),
        ),
    ]
