# Generated by Django 3.2.4 on 2022-01-24 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0050_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification',
            field=models.CharField(choices=[('V', 'Verified'), ('NV', 'Not Verified')], default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no_verification',
            field=models.CharField(choices=[('V', 'Verified'), ('NV', 'Not Verified')], default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
    ]
