# Generated by Django 3.2.4 on 2022-01-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0055_auto_20220124_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verification',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_no_verification',
        ),
        migrations.AddField(
            model_name='profile',
            name='flag',
            field=models.CharField(choices=[('CM', 'Completed'), ('P', 'Pending'), ('C', 'Canceled')], max_length=2, null=True),
        ),
    ]
