# Generated by Django 3.2.4 on 2022-01-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0064_auto_20220124_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verification',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_no_verification',
        ),
        migrations.AddField(
            model_name='profile',
            name='a',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
