# Generated by Django 3.2.4 on 2022-01-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0068_auto_20220124_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_no_otp',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no_otp',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
