# Generated by Django 3.2.4 on 2022-01-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0069_auto_20220126_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_no_otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no_otp',
            field=models.IntegerField(null=True),
        ),
    ]
