# Generated by Django 3.2.4 on 2022-02-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0075_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_point_phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_point_phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
