# Generated by Django 3.2.4 on 2022-02-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0076_auto_20220215_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_point_phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_point_phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
