# Generated by Django 3.2.4 on 2022-02-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0079_auto_20220216_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
