# Generated by Django 3.2.4 on 2022-03-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeDeliver', '0083_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default='2021-09-03'),
            preserve_default=False,
        ),
    ]
