# Generated by Django 3.2.4 on 2021-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('remember_me', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point_name', models.CharField(max_length=50)),
                ('pickup_point_address', models.CharField(max_length=100)),
                ('pickup_point_phone_number', models.CharField(max_length=10)),
                ('delivery_point_name', models.CharField(max_length=50)),
                ('delivery_point_address', models.CharField(max_length=100)),
                ('delivery_point_phone_number', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=2)),
                ('mode_of_payment', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('re_write_password', models.CharField(max_length=20)),
            ],
        ),
    ]
