# Generated by Django 3.2.4 on 2021-09-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagedelivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_form',
            new_name='login',
        ),
    ]
