# Generated by Django 3.2.4 on 2021-09-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedelivery', '0002_auto_20210926_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode_of_payemnt',
            field=models.CharField(choices=[('Credit/Debit Card', 'Credit/Debit Card'), ('Net-Banking', 'Net-Banking'), ('UPI/QR', 'UPI/QR'), ('Pay on Delivery', 'Pay on Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.CharField(choices=[('1', 'Up to 1 kg'), ('5', 'Up to 5 kg'), ('10', 'Up to 10 kg'), ('15', 'Up to 15 kg'), ('20', 'Up to 20 kg')], max_length=2),
        ),
    ]
