# Generated by Django 3.2.4 on 2021-09-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagedelivery', '0003_auto_20210926_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mode_of_payemnt',
        ),
    ]
