# Generated by Django 3.2.4 on 2021-09-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedelivery', '0004_remove_order_mode_of_payemnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_point_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_point_address',
            field=models.CharField(max_length=100),
        ),
    ]
