# Generated by Django 3.2.4 on 2021-09-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedelivery', '0005_auto_20210926_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode_of_payemnt',
            field=models.CharField(choices=[('Credit/Debit Card', 'Credit/Debit Card'), ('Net-Banking', 'Net-Banking'), ('UPI/QR', 'UPI/QR'), ('Pay on Delivery', 'Pay on Delivery')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
