# Generated by Django 3.2.4 on 2021-09-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagedelivery', '0008_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
