# Generated by Django 3.2.4 on 2021-09-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedelivery', '0009_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
